// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskPomodoro.API.Data;

#nullable disable

namespace TaskPomodoro.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250501003535_AddSessaoPomodoro")]
    partial class AddSessaoPomodoro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("TaskPomodoro.API.Models.SessaoPomodoro", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Concluido")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TarefaID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("TarefaID");

                    b.ToTable("SessoesPomodoro");
                });

            modelBuilder.Entity("TaskPomodoro.API.Models.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Concluida")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataConclusao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PomodorosConcluidos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PomodorosRestantes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TempoEstimado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TempoGasto")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tarefas");
                });

            modelBuilder.Entity("TaskPomodoro.API.Models.SessaoPomodoro", b =>
                {
                    b.HasOne("TaskPomodoro.API.Models.Tarefa", "Tarefa")
                        .WithMany()
                        .HasForeignKey("TarefaID");

                    b.Navigation("Tarefa");
                });
#pragma warning restore 612, 618
        }
    }
}
